# Generated by Django 2.2.9 on 2021-01-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='indexing',
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
