# Generated by Django 3.1.5 on 2021-01-25 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0003_analysis_detectionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detectionmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detectionmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='detectionmodel',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detectionmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
