# Generated by Django 3.1.5 on 2021-01-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0004_auto_20210125_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='detectionmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
