# Generated by Django 3.1.5 on 2021-01-27 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0005_auto_20210125_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetectionModel',
            new_name='Pipeline',
        ),
        migrations.RenameField(
            model_name='pipeline',
            old_name='pipeline',
            new_name='nodes',
        ),
    ]
