# Generated by Django 3.1.5 on 2021-01-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0007_auto_20210127_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='data_options',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='model',
            field=models.JSONField(default=list),
        ),
    ]
