# Generated by Django 3.1.5 on 2021-02-03 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0008_auto_20210128_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ts_project.client', to_field='name'),
        ),
    ]
