# Generated by Django 3.1.5 on 2021-03-12 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('ts_project', '0009_auto_20210203_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='disabled')),
                ('time_interval', models.TextField(choices=[('1 min', 'One Min'), ('5 mins', 'Five Mins'), ('1 hour', 'One Hour')], default='1 min')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ts_project.analysis')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
            options={
                'db_table': 'periodic_analysis',
            },
        ),
    ]
