# Generated by Django 3.1.5 on 2021-03-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0011_auto_20210315_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicanalysis',
            name='time_interval',
            field=models.TextField(default='1h'),
        ),
    ]
