# Generated by Django 3.1.5 on 2021-03-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0012_auto_20210315_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodicanalysis',
            name='status',
        ),
        migrations.AddField(
            model_name='periodicanalysis',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
