# Generated by Django 3.1.5 on 2021-04-24 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0014_periodicanalysis_alerts_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'monitors',
            },
        ),
        migrations.AddField(
            model_name='periodicanalysis',
            name='monitors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ts_project.monitor'),
        ),
    ]
