# Generated by Django 3.1.5 on 2021-04-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0015_auto_20210424_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodicanalysis',
            old_name='monitors',
            new_name='monitor',
        ),
        migrations.AddField(
            model_name='monitor',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
