# Generated by Django 3.1.5 on 2021-04-27 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0016_auto_20210426_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeriodicAnalysis',
        ),
    ]
