# Generated by Django 3.1.5 on 2021-04-27 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('ts_project', '0017_delete_periodicanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('alerts_enabled', models.BooleanField(default=False)),
                ('time_interval', models.TextField(default='1h')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ts_project.analysis')),
                ('monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ts_project.monitor')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
            options={
                'db_table': 'periodic_analysis',
            },
        ),
    ]
