# Generated by Django 3.1.5 on 2021-05-07 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0019_auto_20210505_0340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodicanalysis',
            options={'ordering': ['created']},
        ),
    ]
