# Generated by Django 3.1.5 on 2021-05-18 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0021_auto_20210517_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('score', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('desc', models.TextField(null=True)),
                ('periodic_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='ts_project.periodicanalysis')),
            ],
            options={
                'db_table': 'incidents',
            },
        ),
    ]
