# Generated by Django 3.1.5 on 2021-05-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0022_incidents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='created',
        ),
        migrations.AddField(
            model_name='results',
            name='run_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
