# Generated by Django 3.1.5 on 2021-06-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0023_auto_20210518_2311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incidents',
            new_name='Incident',
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['start']},
        ),
        migrations.AlterField(
            model_name='analysis',
            name='data_options',
            field=models.JSONField(default=list),
        ),
    ]
