# Generated by Django 3.1.5 on 2021-06-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0024_auto_20210604_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='client',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
