# Generated by Django 3.1.5 on 2021-07-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0025_incident_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodicanalysis',
            name='relevant_period',
        ),
        migrations.AddField(
            model_name='periodicanalysis',
            name='anomaly_relevant_period',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='periodicanalysis',
            name='data_relevant_period',
            field=models.TextField(default=''),
        ),
    ]
