# Generated by Django 3.1.5 on 2021-07-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0026_auto_20210723_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodicanalysis',
            old_name='anomaly_relevant_period',
            new_name='anomaly_time_window',
        ),
        migrations.RenameField(
            model_name='periodicanalysis',
            old_name='data_relevant_period',
            new_name='data_time_window',
        ),
    ]
