# Generated by Django 3.1.5 on 2021-09-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0027_auto_20210725_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='UTCOffset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='interval',
            field=models.TextField(default='1h'),
        ),
    ]
