# Generated by Django 3.1.5 on 2021-09-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0028_auto_20210903_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='UTCOffset',
        ),
        migrations.AddField(
            model_name='client',
            name='UTCOffset',
            field=models.IntegerField(default=0),
        ),
    ]
