# Generated by Django 3.1.5 on 2021-09-08 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0029_auto_20210907_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='UTCOffset',
            new_name='utc_offset',
        ),
    ]
