# Generated by Django 3.1.5 on 2021-11-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0030_auto_20210908_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
