# Generated by Django 3.1.5 on 2021-11-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_project', '0031_incident_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('anomalies', models.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'test_sets',
            },
        ),
    ]
